### ISSUE TITLE
Intuitive naming

### ISSUE THREAD

**Issue by zachChilders** [Microsoft/Cluster#12]
Right now, storage accounts and key vault names are completely random at all levels.  It would be nice if it would reflect at what level of the topology hierarchy it exists at, and make it much easier to find in azure portal.

**Comment by chriskuech** [comment]
Storage Accounts and Key Vaults are _globally unique_, meaning that their hostname is publicly exposed.  These are intentionally randomized to avoid collisions and add anonymity.  You should always use Resource Group view in Portal and [`-ResourceGroupName` parameter in PowerShell](https://github.com/Microsoft/Cluster#accessing-underlying-resources) in PowerShell
