### ISSUE TITLE
Cluster has almost entirely stopped giving error messages

### ISSUE THREAD

**Issue by zachChilders** [Microsoft/Cluster#19]
This is potentially an AzureRM bug, but DSC deployments have been failing and errors are only listed in portal instead of in the terminal

**Comment by chriskuech** [comment]
I just reproed the situation.  PowerShell methods don't propagate error stream.  All errors must be explicitly thrown.  Errors from called cmdlets should be saved to a variable with `-ErrorVariable` and thrown if not empty.

**Comment by chriskuech** [comment]
#5
