### ISSUE TITLE
ATM

### ISSUE THREAD

**Issue by zachChilders** [Microsoft/Cluster#3]
Azure Traffic Manager integration should be supported out of the box

**Comment by chriskuech** [comment]
We just want one Traffic Manager per Environment to join all its Clusters together, right?  We should be able to accomplish this by adding an ATM and ATM Profile to the Environment in Types.ps1 and let users define the ATM Endpoint in their template.json. users would then be responsible for their own code to pull in and out of rotation

**Comment by zachChilders** [comment]
Agreed.  This exists for tracking purposes.

**Comment by chriskuech** [comment]
reassigning and doing needfuls
