### ISSUE TITLE
Errors that occur after submission to ARM will never bubble up

### ISSUE THREAD

**Issue by zachChilders** [Microsoft/Cluster#5]
It's possible for a deployment to succeed in the console, then fail validation immediately in the Azure RM system.  

Repro:  Choose a VM size not available in a region and attempt to deploy it.  As internal users, this is any VM in West US 2.

Perhaps some prevalidation can occur?

**Comment by chriskuech** [comment]
What do you mean "succeed in the console"?  Cluster will return an arm deployment object--does that object say succeeded?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zachChilders** [comment]
It does, but navigating to the portal will reveal a failed deployment and surface the issue.  In the repro case, no scale set is created.
